export const carBrands = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Bugatti",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroën",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "Genesis",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Koenigsegg",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Lotus",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mini",
  "Mitsubishi",
  "Nissan",
  "Pagani",
  "Peugeot",
  "Porsche",
  "Ram",
  "Renault",
  "Rolls-Royce",
  "Saab",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen (VW)",
  "Volvo",
];

export const footerList = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

export const fuels = [
  { id: "fuel", value: "fuel" },
  { id: "gas", value: "gas" },
  { id: "electric", value: "electric" },
];

export const years = [
  { id: "year", value: "year" },
  { id: "2015", value: "2015" },
  { id: "2016", value: "2016" },
  { id: "2017", value: "2017" },
  { id: "2018", value: "2018" },
  { id: "2019", value: "2019" },
  { id: "2020", value: "2020" },
  { id: "2021", value: "2021" },
  { id: "2022", value: "2022" },
  { id: "2023", value: "2023" },
];
